services:
  embyboss:
    image: ghcr.io/dpeak0/dpeak-embybot-v2:latest
    container_name: embyboss
    restart: always
    network_mode: host
    volumes:
      - ./config.json:/app/config.json
      - ./log:/app/log
      - ./logo.png:/app/logo.png
